### ISSUE TITLE
Add cid image attachment support in template

### ISSUE THREAD

**Issue by Its-Alex** [stephane-klein/gibbon-mail#10]
This will be good to allow users to send mails with images from attachment using [cid](https://sendgrid.com/blog/embedding-images-emails-facts/).

Do you think this is a good idea @stephane-klein ?

**Comment by stephane-klein** [comment]
@Its-Alex ok for [cid](https://sendgrid.com/blog/embedding-images-emails-facts/) support 👍 

Some resources:

- https://mjml.io/documentation/#mjml-image
- https://community.nodemailer.com/using-embedded-images/
- https://nodemailer.com/message/attachments/

How to:

- [ ] Add two images in [`/mail-templates/confirm_email/attachments/`](https://github.com/stephane-klein/gibbon-mail/tree/master/mail-templates/confirm_email) folder (there are example files)
- [ ] Update [`/mail-templates/confirm_email/default.mjml`](https://github.com/stephane-klein/gibbon-mail/blob/master/mail-templates/confirm_email/default.mjml) with two `<mj-image src="cid:imagename.png" />`
- [ ] Add all files in `attachments/` folder to attachment [here](https://github.com/stephane-klein/gibbon-mail/blob/master/backend/src/app.js#L148)

**Comment by stephane-klein** [comment]
See also that https://github.com/nodkz/mjml-with-images-loader

**Comment by Its-Alex** [comment]
> See also that [nodkz/mjml-with-images-loader](https://github.com/nodkz/mjml-with-images-loader)

I think this is overkill in our case no ? If we want to add it we must setup webpack
