### ISSUE TITLE
Add documentation about how gibbon-mail works

### ISSUE THREAD

**Issue by Its-Alex** [stephane-klein/gibbon-mail#5]
I think this will be useful to add documentation about:

- How `schema.json` works
- Specify that `from` and `to` are used to send mail
- How to use `swagger.yaml`

**Comment by stephane-klein** [comment]
> How to use swagger.yaml

@Its-Alex swagger is documented in this readme https://github.com/stephane-klein/gibbon-mail/blob/master/backend/README.md

What information do you need about `swagger.yaml`?

**Comment by Its-Alex** [comment]
@stephane-klein Url in API and the way to use it

**Comment by Its-Alex** [comment]
@stephane-klein Ok it's already documented in readme we can't ignore this line
