### ISSUE TITLE
When refreshing on a template page server return not found

### ISSUE THREAD

**Issue by Its-Alex** [stephane-klein/gibbon-mail#6]
When we are viewing a template page, refresh page lead to a 404 not found.

Example with an existing project name hello_world after a refresh:

<img width="1917" alt="Screenshot 2019-11-29 at 10 04 03" src="https://user-images.githubusercontent.com/6404072/69857160-97863600-128f-11ea-8c29-b40b4187e749.png">

**Comment by stephane-klein** [comment]
@Its-Alex I don't understand.

I go to `backend/`, I execute:

```
$ npm install
$ npm run start
```

```
$ curl -i http://127.0.0.1:5000/hello_world/
HTTP/1.1 404 Not Found
Vary: Origin
Content-Type: text/plain; charset=utf-8
Content-Length: 9
Date: Sun, 05 Jan 2020 14:50:11 GMT
Connection: keep-alive

Not Found%
```

this request return 404 error because it is invalid request.

What result do you expect?

**Comment by Its-Alex** [comment]
@stephane-klein I expect to go to template `hello_world`
